# Generated by Django 3.1.3 on 2020-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201204_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bankId',
            field=models.IntegerField(default=73),
        ),
    ]
