# Generated by Django 3.1.3 on 2020-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankaccount_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bankId',
            field=models.IntegerField(default=44),
            preserve_default=False,
        ),
    ]
