# Generated by Django 3.1.3 on 2020-12-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bank_bankid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bankId',
        ),
    ]
