# Generated by Django 3.1.3 on 2020-12-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_bank_bankid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bankId',
            field=models.IntegerField(auto_created=True, default=55),
            preserve_default=False,
        ),
    ]
