# Generated by Django 3.1.3 on 2020-12-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bank_bankid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='id',
        ),
        migrations.AlterField(
            model_name='bank',
            name='bankId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
