# Generated by Django 3.1.3 on 2020-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201205_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='userId',
            field=models.IntegerField(default=73),
        ),
    ]
