# Generated by Django 3.1.3 on 2020-12-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bank_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='startBal',
            field=models.FloatField(default=0.0),
        ),
    ]
